# Generated by Django 3.2.6 on 2022-05-19 21:48

from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Academia',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('academia', models.CharField(max_length=100, verbose_name='academia')),
            ],
            options={
                'verbose_name': 'Departamento',
                'verbose_name_plural': 'Departamentos',
            },
        ),
        migrations.CreateModel(
            name='Alumno',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('state', models.BooleanField(default=True, verbose_name='Estado')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creacion')),
                ('modified_date', models.DateTimeField(auto_now=True, verbose_name='Fecha de modificacion')),
                ('deleted_date', models.DateTimeField(auto_now=True, verbose_name='Fecha de eliminacion')),
                ('fk_user', models.IntegerField(default=0)),
                ('alta_app', models.BooleanField(default=False, verbose_name='Dado de alta en aplicacion')),
                ('email', models.EmailField(max_length=50, verbose_name='Correo Electronico')),
                ('boleta', models.CharField(max_length=50, unique=True, verbose_name='Boleta')),
            ],
            options={
                'verbose_name': 'Alumno',
                'verbose_name_plural': 'Alumnos',
            },
        ),
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('departamento', models.CharField(max_length=100, verbose_name='departamento')),
            ],
            options={
                'verbose_name': 'Departamento',
                'verbose_name_plural': 'Departamentos',
            },
        ),
        migrations.CreateModel(
            name='HistoricalAcademia',
            fields=[
                ('id', models.IntegerField(db_index=True)),
                ('academia', models.CharField(max_length=100, verbose_name='academia')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
            ],
            options={
                'verbose_name': 'historical Departamento',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalDepartamento',
            fields=[
                ('id', models.IntegerField(db_index=True)),
                ('departamento', models.CharField(max_length=100, verbose_name='departamento')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
            ],
            options={
                'verbose_name': 'historical Departamento',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalProgramaAcademico',
            fields=[
                ('id', models.IntegerField(db_index=True)),
                ('programa', models.CharField(max_length=50, verbose_name='Descripccion del programa academico')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
            ],
            options={
                'verbose_name': 'historical Programa Academico',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='ProgramaAcademico',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('programa', models.CharField(max_length=50, verbose_name='Descripccion del programa academico')),
            ],
            options={
                'verbose_name': 'Programa Academico',
                'verbose_name_plural': 'Programas Academicos',
            },
        ),
        migrations.CreateModel(
            name='Profesor',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('state', models.BooleanField(default=True, verbose_name='Estado')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creacion')),
                ('modified_date', models.DateTimeField(auto_now=True, verbose_name='Fecha de modificacion')),
                ('deleted_date', models.DateTimeField(auto_now=True, verbose_name='Fecha de eliminacion')),
                ('fk_user', models.IntegerField(default=0)),
                ('alta_app', models.BooleanField(default=False, verbose_name='Dado de alta en aplicacion')),
                ('email', models.EmailField(max_length=50, unique=True, verbose_name='Correo Electronico')),
                ('noEmpleado', models.CharField(blank=True, max_length=50, null=True, verbose_name='Numero de noEmpleado')),
                ('fk_academia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comunidad.academia', verbose_name='fk_academia')),
            ],
            options={
                'verbose_name': 'Profesor',
                'verbose_name_plural': 'Profesores',
            },
        ),
    ]
