# Generated by Django 3.2.6 on 2022-04-30 02:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('comunidad', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalprogramaacademico',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicaldepartamento',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='alumno',
            name='fk_programa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comunidad.programaacademico', verbose_name='pk de programa academico'),
        ),
    ]
