# Generated by Django 3.2.6 on 2022-04-16 06:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comunidad', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historicalprogramaacademico',
            options={'get_latest_by': 'history_date', 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Programa Academico'},
        ),
        migrations.AlterModelOptions(
            name='programaacademico',
            options={'verbose_name': 'Programa Academico', 'verbose_name_plural': 'Programas Academicos'},
        ),
        migrations.CreateModel(
            name='Alumno',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('state', models.BooleanField(default=True, verbose_name='Estado')),
                ('created_date', models.DateField(auto_now_add=True, verbose_name='Fecha de creacion')),
                ('modified_date', models.DateField(auto_now=True, verbose_name='Fecha de modificacion')),
                ('deleted_date', models.DateField(auto_now=True, verbose_name='Fecha de eliminacion')),
                ('fk_user', models.IntegerField(default=0)),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='Correo Electronico')),
                ('boleta', models.CharField(blank=True, max_length=255, null=True, verbose_name='Boleta')),
                ('fk_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comunidad.programaacademico', verbose_name='pk de equipo')),
            ],
            options={
                'verbose_name': 'Alumno',
                'verbose_name_plural': 'Alumnos',
            },
        ),
    ]
