# Generated by Django 3.2.6 on 2022-05-01 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comunidad', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumno',
            name='boleta',
            field=models.CharField(max_length=50, unique=True, verbose_name='Boleta'),
        ),
        migrations.AlterField(
            model_name='alumno',
            name='email',
            field=models.EmailField(max_length=50, verbose_name='Correo Electronico'),
        ),
        migrations.AlterField(
            model_name='departamento',
            name='departamento',
            field=models.CharField(max_length=75, verbose_name='Departamento escolar'),
        ),
        migrations.AlterField(
            model_name='historicaldepartamento',
            name='departamento',
            field=models.CharField(max_length=75, verbose_name='Departamento escolar'),
        ),
        migrations.AlterField(
            model_name='historicalprogramaacademico',
            name='programa',
            field=models.CharField(max_length=50, verbose_name='Descripccion del programa academico'),
        ),
        migrations.AlterField(
            model_name='profesor',
            name='email',
            field=models.EmailField(max_length=50, unique=True, verbose_name='Correo Electronico'),
        ),
        migrations.AlterField(
            model_name='profesor',
            name='noEmpleado',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Numero de noEmpleado'),
        ),
        migrations.AlterField(
            model_name='programaacademico',
            name='programa',
            field=models.CharField(max_length=50, verbose_name='Descripccion del programa academico'),
        ),
    ]
