# Generated by Django 3.2.6 on 2022-05-21 02:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comunidad', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='academia',
            options={'verbose_name': 'Academias', 'verbose_name_plural': 'Acedemias'},
        ),
        migrations.AlterModelOptions(
            name='historicalacademia',
            options={'get_latest_by': 'history_date', 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Academias'},
        ),
    ]
