# Generated by Django 3.2.6 on 2022-04-16 21:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('comunidad', '0003_rename_fk_team_alumno_fk_programa'),
    ]

    operations = [
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('departamento', models.CharField(max_length=255, verbose_name='Departamento escolar')),
            ],
            options={
                'verbose_name': 'Departamento',
                'verbose_name_plural': 'Departamentos',
            },
        ),
        migrations.AddField(
            model_name='alumno',
            name='resumenProfesional',
            field=models.TextField(blank=True, null=True, verbose_name='Resumen profesional'),
        ),
        migrations.AlterField(
            model_name='alumno',
            name='fk_programa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comunidad.programaacademico', verbose_name='pk de alumno'),
        ),
        migrations.CreateModel(
            name='Profesor',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('state', models.BooleanField(default=True, verbose_name='Estado')),
                ('created_date', models.DateField(auto_now_add=True, verbose_name='Fecha de creacion')),
                ('modified_date', models.DateField(auto_now=True, verbose_name='Fecha de modificacion')),
                ('deleted_date', models.DateField(auto_now=True, verbose_name='Fecha de eliminacion')),
                ('fk_user', models.IntegerField(default=0)),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='Correo Electronico')),
                ('noEmpleado', models.CharField(blank=True, max_length=255, null=True, verbose_name='Numero de noEmpleado')),
                ('resumenProfesional', models.TextField(blank=True, null=True, verbose_name='Resumen profesional')),
                ('fk_programa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comunidad.departamento', verbose_name='pk de profesor')),
            ],
            options={
                'verbose_name': 'Profesor',
                'verbose_name_plural': 'Profesores',
            },
        ),
        migrations.CreateModel(
            name='HistoricalDepartamento',
            fields=[
                ('id', models.IntegerField(db_index=True)),
                ('departamento', models.CharField(max_length=255, verbose_name='Departamento escolar')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Departamento',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
