# Generated by Django 3.2.6 on 2022-06-06 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comunidad', '0003_auto_20220520_2105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profesor',
            name='alta_app',
            field=models.BooleanField(default=False, verbose_name='alta_app'),
        ),
        migrations.AlterField(
            model_name='profesor',
            name='email',
            field=models.EmailField(max_length=50, unique=True, verbose_name='email'),
        ),
        migrations.AlterField(
            model_name='profesor',
            name='noEmpleado',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='noEmpleado'),
        ),
    ]
