# Generated by Django 3.2.6 on 2022-06-06 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comunidad', '0004_auto_20220605_2225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumno',
            name='alta_app',
            field=models.BooleanField(default=False, verbose_name='alta_app'),
        ),
        migrations.AlterField(
            model_name='alumno',
            name='boleta',
            field=models.CharField(max_length=50, unique=True, verbose_name='boleta'),
        ),
        migrations.AlterField(
            model_name='alumno',
            name='email',
            field=models.EmailField(max_length=50, verbose_name='email'),
        ),
    ]
