# Generated by Django 3.2.6 on 2022-04-16 21:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comunidad', '0004_auto_20220416_1631'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profesor',
            old_name='fk_programa',
            new_name='fk_departamento',
        ),
    ]
