# Generated by Django 3.2.6 on 2022-04-16 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comunidad', '0005_rename_fk_programa_profesor_fk_departamento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumno',
            name='resumenProfesional',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Resumen profesional'),
        ),
        migrations.AlterField(
            model_name='profesor',
            name='resumenProfesional',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Resumen profesional'),
        ),
    ]
