# Generated by Django 3.2.6 on 2022-04-16 22:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comunidad', '0006_auto_20220416_1654'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alumno',
            name='resumenProfesional',
        ),
        migrations.RemoveField(
            model_name='profesor',
            name='resumenProfesional',
        ),
    ]
