# Generated by Django 3.2.6 on 2022-04-17 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comunidad', '0007_auto_20220416_1701'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumno',
            name='alta_app',
            field=models.BooleanField(default=False, verbose_name='Dado de alta en aplicacion'),
        ),
    ]
