# Generated by Django 3.2.6 on 2022-04-17 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comunidad', '0008_alumno_alta_app'),
    ]

    operations = [
        migrations.AddField(
            model_name='profesor',
            name='alta_app',
            field=models.BooleanField(default=False, verbose_name='Dado de alta en aplicacion'),
        ),
    ]
