# Generated by Django 3.2.6 on 2022-04-18 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comunidad', '0012_auto_20220417_2143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumno',
            name='email',
            field=models.EmailField(max_length=255, verbose_name='Correo Electronico'),
        ),
    ]
