# Generated by Django 3.2.6 on 2022-04-24 06:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comunidad', '0014_alter_alumno_fk_programa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profesor',
            name='fk_departamento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comunidad.departamento', verbose_name='fk_departamento'),
        ),
    ]
