# Generated by Django 3.2.6 on 2022-04-24 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comunidad', '0015_alter_profesor_fk_departamento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumno',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creacion'),
        ),
        migrations.AlterField(
            model_name='profesor',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creacion'),
        ),
    ]
