# Generated by Django 3.2.6 on 2022-04-30 02:39

from django.db import migrations, models
import simple_history.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Firma',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('state', models.BooleanField(default=True, verbose_name='Estado')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creacion')),
                ('modified_date', models.DateTimeField(auto_now=True, verbose_name='Fecha de modificacion')),
                ('deleted_date', models.DateTimeField(auto_now=True, verbose_name='Fecha de eliminacion')),
                ('password_firma', models.CharField(max_length=50, verbose_name='Password de firma')),
                ('ruta_public_key', models.CharField(max_length=250, verbose_name='Llave publica de certificado')),
                ('ruta_private_key', models.CharField(max_length=250, verbose_name='Llave privada de certificado')),
            ],
            options={
                'verbose_name': 'Firma',
                'verbose_name_plural': 'Firmas',
            },
        ),
        migrations.CreateModel(
            name='HistoricalFirma',
            fields=[
                ('id', models.IntegerField(blank=True, db_index=True)),
                ('state', models.BooleanField(default=True, verbose_name='Estado')),
                ('created_date', models.DateTimeField(blank=True, editable=False, verbose_name='Fecha de creacion')),
                ('modified_date', models.DateTimeField(blank=True, editable=False, verbose_name='Fecha de modificacion')),
                ('deleted_date', models.DateTimeField(blank=True, editable=False, verbose_name='Fecha de eliminacion')),
                ('password_firma', models.CharField(max_length=50, verbose_name='Password de firma')),
                ('ruta_public_key', models.CharField(max_length=250, verbose_name='Llave publica de certificado')),
                ('ruta_private_key', models.CharField(max_length=250, verbose_name='Llave privada de certificado')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
            ],
            options={
                'verbose_name': 'historical Firma',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
