# Generated by Django 3.2.6 on 2022-04-30 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firma', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='firma',
            name='vigencia_firma',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalfirma',
            name='vigencia_firma',
            field=models.DateField(blank=True, editable=False, null=True),
        ),
    ]
