# Generated by Django 3.2.6 on 2022-04-30 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firma', '0003_auto_20220429_2237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='firma',
            name='vigencia_firma',
            field=models.DateField(auto_now=True, null=True),
        ),
    ]
