# Generated by Django 3.2.6 on 2022-06-05 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firma', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='firmaprotocolo',
            name='firma_sat',
            field=models.BooleanField(default=False, verbose_name='firma_sat'),
        ),
        migrations.AddField(
            model_name='historicalfirmaprotocolo',
            name='firma_sat',
            field=models.BooleanField(default=False, verbose_name='firma_sat'),
        ),
    ]
