# Generated by Django 3.2.6 on 2022-04-30 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firma', '0004_alter_firma_vigencia_firma'),
    ]

    operations = [
        migrations.AlterField(
            model_name='firma',
            name='vigencia_firma',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historicalfirma',
            name='vigencia_firma',
            field=models.DateField(blank=True, null=True),
        ),
    ]
