# Generated by Django 3.2.6 on 2022-05-08 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firma', '0005_auto_20220429_2255'),
    ]

    operations = [
        migrations.AddField(
            model_name='firma',
            name='ruta_firma',
            field=models.CharField(default='', max_length=250, verbose_name='Ruta donde se guardan los archivos'),
        ),
        migrations.AddField(
            model_name='historicalfirma',
            name='ruta_firma',
            field=models.CharField(default='', max_length=250, verbose_name='Ruta donde se guardan los archivos'),
        ),
    ]
