# Generated by Django 3.2.6 on 2022-05-09 04:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('protocol', '0007_auto_20220502_0108'),
        ('firma', '0007_firmaprotocolo_historicalfirmaprotocolo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='firmaprotocolo',
            options={'verbose_name': 'FirmaProtocolo', 'verbose_name_plural': 'FirmasProtocolo'},
        ),
        migrations.AlterModelOptions(
            name='historicalfirmaprotocolo',
            options={'get_latest_by': 'history_date', 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical FirmaProtocolo'},
        ),
        migrations.AlterField(
            model_name='firmaprotocolo',
            name='fk_protocol',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='protocol.protocol', verbose_name='pk de protocolo'),
        ),
        migrations.AlterField(
            model_name='historicalfirmaprotocolo',
            name='fk_protocol',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='protocol.protocol', verbose_name='pk de protocolo'),
        ),
    ]
