# Generated by Django 3.2.6 on 2022-05-09 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firma', '0008_auto_20220508_2300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='firmaprotocolo',
            name='firma',
            field=models.CharField(default='', max_length=400, verbose_name='firma de protocolo'),
        ),
        migrations.AlterField(
            model_name='historicalfirmaprotocolo',
            name='firma',
            field=models.CharField(default='', max_length=400, verbose_name='firma de protocolo'),
        ),
    ]
