# Generated by Django 3.2.6 on 2022-05-14 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firma', '0009_auto_20220509_0016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='firma',
            name='vigencia_firma',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de eliminacion'),
        ),
        migrations.AlterField(
            model_name='historicalfirma',
            name='vigencia_firma',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de eliminacion'),
        ),
    ]
