# Generated by Django 3.2.6 on 2022-05-14 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firma', '0010_auto_20220514_1801'),
    ]

    operations = [
        migrations.AlterField(
            model_name='firma',
            name='vigencia_firma',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historicalfirma',
            name='vigencia_firma',
            field=models.DateField(blank=True, null=True),
        ),
    ]
