# Generated by Django 3.2.6 on 2022-04-16 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaluser',
            name='professionalSummary',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Resumen profesional'),
        ),
        migrations.AddField(
            model_name='user',
            name='professionalSummary',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Resumen profesional'),
        ),
    ]
