# Generated by Django 3.2.6 on 2022-04-16 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20220416_1701'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaluser',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Telefono'),
        ),
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Telefono'),
        ),
    ]
