# Generated by Django 3.2.6 on 2022-04-18 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20220416_1712'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaluser',
            name='rol_user',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='rol_user',
            field=models.IntegerField(default=0),
        ),
    ]
