# Generated by Django 3.2.6 on 2022-04-21 02:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20220420_2132'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicaluser',
            name='code_activate_confirm',
        ),
        migrations.RemoveField(
            model_name='user',
            name='code_activate_confirm',
        ),
    ]
