# Generated by Django 3.2.6 on 2022-05-19 21:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('team', '0001_initial'),
        ('notification', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificacionteam',
            name='fk_userDestino',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='team.teammembers', verbose_name='Relacion de miembro de equipo a relacionar'),
        ),
    ]
