# Generated by Django 3.2.6 on 2022-04-24 19:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0002_notificacion_fk_userdestino'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historicaltiponotificacion',
            options={'get_latest_by': 'history_date', 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Tipo de notificacion'},
        ),
        migrations.AlterModelOptions(
            name='tiponotificacion',
            options={'verbose_name': 'Tipo de notificacion', 'verbose_name_plural': 'Tipo de notificaciones'},
        ),
    ]
