# Generated by Django 3.2.6 on 2022-06-06 07:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('notification', '0002_notificacionteam_fk_userdestino'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificacionteam',
            name='fk_userOrigen',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='pk de usuario que genera notificacion'),
        ),
        migrations.AddField(
            model_name='historicaltiponotificacion',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
    ]
