# Generated by Django 3.2.6 on 2022-04-24 23:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0004_alter_notificacion_created_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificacion',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de creacion'),
        ),
    ]
