# Generated by Django 3.2.6 on 2022-04-26 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0005_alter_notificacion_created_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificacion',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creacion'),
        ),
    ]
