# Generated by Django 3.2.6 on 2022-04-27 01:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('team', '0013_auto_20220426_1507'),
        ('notification', '0006_alter_notificacion_created_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificacionTeam',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('state', models.BooleanField(default=True, verbose_name='Estado')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creacion')),
                ('modified_date', models.DateField(auto_now=True, verbose_name='Fecha de modificacion')),
                ('deleted_date', models.DateField(auto_now=True, verbose_name='Fecha de eliminacion')),
                ('fk_tipoNotificacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notification.tiponotificacion', verbose_name='pk tipo de notificacion')),
                ('fk_userDestino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='team.teammembers', verbose_name='Relacion de miembro de equipo a relacionar')),
                ('fk_userOrigen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='pk de usuario que genera notificacion')),
            ],
            options={
                'verbose_name': 'Notificacion equipo',
                'verbose_name_plural': 'Notificaciones equipo',
            },
        ),
        migrations.DeleteModel(
            name='Notificacion',
        ),
    ]
