# Generated by Django 3.2.6 on 2022-05-19 21:48

import apps.protocol.models
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='catInscripccion',
            fields=[
                ('state', models.BooleanField(default=True, verbose_name='Estado')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creacion')),
                ('modified_date', models.DateTimeField(auto_now=True, verbose_name='Fecha de modificacion')),
                ('deleted_date', models.DateTimeField(auto_now=True, verbose_name='Fecha de eliminacion')),
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('descp', models.CharField(max_length=50, verbose_name='catalogo inscripccion')),
            ],
            options={
                'verbose_name': 'inscripccion',
                'verbose_name_plural': 'inscripcciones',
            },
        ),
        migrations.CreateModel(
            name='HistoricalcatInscripccion',
            fields=[
                ('state', models.BooleanField(default=True, verbose_name='Estado')),
                ('created_date', models.DateTimeField(blank=True, editable=False, verbose_name='Fecha de creacion')),
                ('modified_date', models.DateTimeField(blank=True, editable=False, verbose_name='Fecha de modificacion')),
                ('deleted_date', models.DateTimeField(blank=True, editable=False, verbose_name='Fecha de eliminacion')),
                ('id', models.IntegerField(db_index=True)),
                ('descp', models.CharField(max_length=50, verbose_name='catalogo inscripccion')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
            ],
            options={
                'verbose_name': 'historical inscripccion',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalkeyWord',
            fields=[
                ('id', models.IntegerField(blank=True, db_index=True)),
                ('state', models.BooleanField(default=True, verbose_name='Estado')),
                ('created_date', models.DateTimeField(blank=True, editable=False, verbose_name='Fecha de creacion')),
                ('modified_date', models.DateTimeField(blank=True, editable=False, verbose_name='Fecha de modificacion')),
                ('deleted_date', models.DateTimeField(blank=True, editable=False, verbose_name='Fecha de eliminacion')),
                ('word', models.CharField(max_length=50, verbose_name='Palabra clave')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
            ],
            options={
                'verbose_name': 'historical Palabra clave',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalPeriodoEscolar',
            fields=[
                ('id', models.IntegerField(blank=True, db_index=True)),
                ('state', models.BooleanField(default=True, verbose_name='Estado')),
                ('created_date', models.DateTimeField(blank=True, editable=False, verbose_name='Fecha de creacion')),
                ('modified_date', models.DateTimeField(blank=True, editable=False, verbose_name='Fecha de modificacion')),
                ('deleted_date', models.DateTimeField(blank=True, editable=False, verbose_name='Fecha de eliminacion')),
                ('periodo', models.IntegerField(verbose_name='periodo')),
                ('anio', models.IntegerField(verbose_name='anio')),
                ('descp', models.CharField(max_length=50, verbose_name='Descripccion')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
            ],
            options={
                'verbose_name': 'historical Periodo escolar',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalProtocol',
            fields=[
                ('id', models.IntegerField(blank=True, db_index=True)),
                ('state', models.BooleanField(default=True, verbose_name='Estado')),
                ('created_date', models.DateTimeField(blank=True, editable=False, verbose_name='Fecha de creacion')),
                ('modified_date', models.DateTimeField(blank=True, editable=False, verbose_name='Fecha de modificacion')),
                ('deleted_date', models.DateTimeField(blank=True, editable=False, verbose_name='Fecha de eliminacion')),
                ('number', models.CharField(db_index=True, max_length=10, verbose_name='Numero de protocolo')),
                ('title', models.CharField(max_length=150, verbose_name='Titulo de protocolo')),
                ('sumary', models.TextField(null=True, verbose_name='Resumen de protocolo')),
                ('fileProtocol', models.TextField(blank=True, max_length=100, null=True, verbose_name='Archivo de protocolo')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
            ],
            options={
                'verbose_name': 'historical Protocolo',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalProtocolState',
            fields=[
                ('id', models.IntegerField(blank=True, db_index=True)),
                ('state', models.BooleanField(default=True, verbose_name='Estado')),
                ('created_date', models.DateTimeField(blank=True, editable=False, verbose_name='Fecha de creacion')),
                ('modified_date', models.DateTimeField(blank=True, editable=False, verbose_name='Fecha de modificacion')),
                ('deleted_date', models.DateTimeField(blank=True, editable=False, verbose_name='Fecha de eliminacion')),
                ('protocol_state', models.IntegerField(default=True, verbose_name='Estado protocolo')),
                ('description', models.CharField(db_index=True, max_length=50, verbose_name='Descripccion del estado')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
            ],
            options={
                'verbose_name': 'historical Estado de protocolo',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='keyWord',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('state', models.BooleanField(default=True, verbose_name='Estado')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creacion')),
                ('modified_date', models.DateTimeField(auto_now=True, verbose_name='Fecha de modificacion')),
                ('deleted_date', models.DateTimeField(auto_now=True, verbose_name='Fecha de eliminacion')),
                ('word', models.CharField(max_length=50, verbose_name='Palabra clave')),
            ],
            options={
                'verbose_name': 'Palabra clave',
                'verbose_name_plural': 'Palabras clave',
            },
        ),
        migrations.CreateModel(
            name='PeriodoEscolar',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('state', models.BooleanField(default=True, verbose_name='Estado')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creacion')),
                ('modified_date', models.DateTimeField(auto_now=True, verbose_name='Fecha de modificacion')),
                ('deleted_date', models.DateTimeField(auto_now=True, verbose_name='Fecha de eliminacion')),
                ('periodo', models.IntegerField(verbose_name='periodo')),
                ('anio', models.IntegerField(verbose_name='anio')),
                ('descp', models.CharField(max_length=50, verbose_name='Descripccion')),
            ],
            options={
                'verbose_name': 'Periodo escolar',
                'verbose_name_plural': 'Periodos escolares',
            },
        ),
        migrations.CreateModel(
            name='ProtocolState',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('state', models.BooleanField(default=True, verbose_name='Estado')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creacion')),
                ('modified_date', models.DateTimeField(auto_now=True, verbose_name='Fecha de modificacion')),
                ('deleted_date', models.DateTimeField(auto_now=True, verbose_name='Fecha de eliminacion')),
                ('protocol_state', models.IntegerField(default=True, verbose_name='Estado protocolo')),
                ('description', models.CharField(max_length=50, unique=True, verbose_name='Descripccion del estado')),
            ],
            options={
                'verbose_name': 'Estado de protocolo',
                'verbose_name_plural': 'Estado de protocolos',
            },
        ),
        migrations.CreateModel(
            name='Protocol',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('state', models.BooleanField(default=True, verbose_name='Estado')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creacion')),
                ('modified_date', models.DateTimeField(auto_now=True, verbose_name='Fecha de modificacion')),
                ('deleted_date', models.DateTimeField(auto_now=True, verbose_name='Fecha de eliminacion')),
                ('number', models.CharField(max_length=10, unique=True, verbose_name='Numero de protocolo')),
                ('title', models.CharField(max_length=150, verbose_name='Titulo de protocolo')),
                ('sumary', models.TextField(null=True, verbose_name='Resumen de protocolo')),
                ('fileProtocol', models.FileField(blank=True, null=True, upload_to=apps.protocol.models.user_directory_path, verbose_name='Archivo de protocolo')),
                ('fk_inscripccion', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='protocol.catinscripccion', verbose_name='Perido de inscripccion')),
                ('fk_periodo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='protocol.periodoescolar', verbose_name='Perido de inscripccion')),
                ('fk_protocol_state', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='protocol.protocolstate', verbose_name='Estado del prtocolo')),
            ],
            options={
                'verbose_name': 'Protocolo',
                'verbose_name_plural': 'Protocolos',
            },
        ),
    ]
