# Generated by Django 3.2.6 on 2022-05-19 21:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('team', '0001_initial'),
        ('protocol', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='protocol',
            name='fk_team',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='team.team', verbose_name='Equipo de protocolo'),
        ),
        migrations.AddField(
            model_name='keyword',
            name='fk_Protocol',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='protocol.protocol', verbose_name='pk de prtocolo'),
        ),
    ]
