# Generated by Django 3.2.6 on 2022-06-13 07:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('team', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('comunidad', '0002_initial'),
        ('protocol', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='selectprotocolo',
            name='fk_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='fk_user'),
        ),
        migrations.AddField(
            model_name='protocol',
            name='fk_inscripccion',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='protocol.catinscripccion', verbose_name='Perido de inscripccion'),
        ),
        migrations.AddField(
            model_name='protocol',
            name='fk_periodo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='protocol.periodoescolar', verbose_name='Perido de inscripccion'),
        ),
        migrations.AddField(
            model_name='protocol',
            name='fk_protocol_state',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='protocol.protocolstate', verbose_name='Estado del prtocolo'),
        ),
        migrations.AddField(
            model_name='protocol',
            name='fk_team',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='team.team', verbose_name='Equipo de protocolo'),
        ),
        migrations.AddField(
            model_name='pregunta',
            name='fk_evaluacion',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='protocol.evaluacion', verbose_name='fk_evaluacion'),
        ),
        migrations.AddField(
            model_name='keyword',
            name='fk_Protocol',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='protocol.protocol', verbose_name='pk de prtocolo'),
        ),
        migrations.AddField(
            model_name='historicalselectprotocolo',
            name='fk_protocol',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='protocol.protocol', verbose_name='fk_protocol'),
        ),
        migrations.AddField(
            model_name='historicalselectprotocolo',
            name='fk_user',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='fk_user'),
        ),
        migrations.AddField(
            model_name='historicalselectprotocolo',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalprotocolstate',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalprotocol',
            name='fk_inscripccion',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='protocol.catinscripccion', verbose_name='Perido de inscripccion'),
        ),
        migrations.AddField(
            model_name='historicalprotocol',
            name='fk_periodo',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='protocol.periodoescolar', verbose_name='Perido de inscripccion'),
        ),
        migrations.AddField(
            model_name='historicalprotocol',
            name='fk_protocol_state',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='protocol.protocolstate', verbose_name='Estado del prtocolo'),
        ),
        migrations.AddField(
            model_name='historicalprotocol',
            name='fk_team',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='team.team', verbose_name='Equipo de protocolo'),
        ),
        migrations.AddField(
            model_name='historicalprotocol',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalpregunta',
            name='fk_evaluacion',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='protocol.evaluacion', verbose_name='fk_evaluacion'),
        ),
        migrations.AddField(
            model_name='historicalpregunta',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalperiodoescolar',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalkeyword',
            name='fk_Protocol',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='protocol.protocol', verbose_name='pk de prtocolo'),
        ),
        migrations.AddField(
            model_name='historicalkeyword',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalevaluacion',
            name='fk_seleccion',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='protocol.selectprotocolo', verbose_name='fk_seleccion'),
        ),
        migrations.AddField(
            model_name='historicalevaluacion',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalcatinscripccion',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalasignacionprotocolo',
            name='fk_academia',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='comunidad.academia', verbose_name='fk_academia'),
        ),
        migrations.AddField(
            model_name='historicalasignacionprotocolo',
            name='fk_protocol',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='protocol.protocol', verbose_name='fk_protocol'),
        ),
        migrations.AddField(
            model_name='historicalasignacionprotocolo',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='evaluacion',
            name='fk_seleccion',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='protocol.selectprotocolo', verbose_name='fk_seleccion'),
        ),
        migrations.AddField(
            model_name='asignacionprotocolo',
            name='fk_academia',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='comunidad.academia', verbose_name='fk_academia'),
        ),
        migrations.AddField(
            model_name='asignacionprotocolo',
            name='fk_protocol',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='protocol.protocol', verbose_name='fk_protocol'),
        ),
    ]
