# Generated by Django 3.2.6 on 2022-03-07 05:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('protocol', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalprotocol',
            name='sumary',
            field=models.TextField(null=True, verbose_name='Resumen de protocolo'),
        ),
        migrations.AlterField(
            model_name='protocol',
            name='protocol_state',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='protocol.protocolstate', verbose_name='Estado del prtocolo'),
        ),
        migrations.AlterField(
            model_name='protocol',
            name='sumary',
            field=models.TextField(null=True, verbose_name='Resumen de protocolo'),
        ),
    ]
