# Generated by Django 3.2.6 on 2022-05-01 04:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('protocol', '0003_historicalperiodoescolar_periodoescolar'),
    ]

    operations = [
        migrations.CreateModel(
            name='catInscripccion',
            fields=[
                ('state', models.BooleanField(default=True, verbose_name='Estado')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creacion')),
                ('modified_date', models.DateTimeField(auto_now=True, verbose_name='Fecha de modificacion')),
                ('deleted_date', models.DateTimeField(auto_now=True, verbose_name='Fecha de eliminacion')),
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('descp', models.CharField(max_length=50, verbose_name='catalogo inscripccion')),
            ],
            options={
                'verbose_name': 'inscripccion',
                'verbose_name_plural': 'inscripcciones',
            },
        ),
        migrations.CreateModel(
            name='HistoricalcatInscripccion',
            fields=[
                ('state', models.BooleanField(default=True, verbose_name='Estado')),
                ('created_date', models.DateTimeField(blank=True, editable=False, verbose_name='Fecha de creacion')),
                ('modified_date', models.DateTimeField(blank=True, editable=False, verbose_name='Fecha de modificacion')),
                ('deleted_date', models.DateTimeField(blank=True, editable=False, verbose_name='Fecha de eliminacion')),
                ('id', models.IntegerField(db_index=True)),
                ('descp', models.CharField(max_length=50, verbose_name='catalogo inscripccion')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical inscripccion',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
