# Generated by Django 3.2.6 on 2022-03-07 07:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('protocol', '0004_alter_protocol_protocol_state'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalprotocol',
            name='protocol_state',
        ),
        migrations.RemoveField(
            model_name='protocol',
            name='protocol_state',
        ),
    ]
