# Generated by Django 3.2.6 on 2022-05-02 05:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('protocol', '0005_auto_20220501_2342'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalprotocol',
            name='inscripccion',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='protocol.catinscripccion', verbose_name='Perido de inscripccion'),
        ),
        migrations.AddField(
            model_name='protocol',
            name='inscripccion',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='protocol.catinscripccion', verbose_name='Perido de inscripccion'),
        ),
    ]
