# Generated by Django 3.2.6 on 2022-03-07 07:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('protocol', '0005_auto_20220307_0745'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalprotocol',
            name='protocol_state',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='protocol.protocolstate', verbose_name='Estado del prtocolo'),
        ),
        migrations.AddField(
            model_name='protocol',
            name='protocol_state',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='protocol.protocolstate', verbose_name='Estado del prtocolo'),
        ),
    ]
