# Generated by Django 3.2.6 on 2022-05-23 06:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('protocol', '0005_historicalselectprotocolo_selectprotocolo'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalEvaluacion',
            fields=[
                ('id', models.IntegerField(blank=True, db_index=True)),
                ('state', models.BooleanField(default=True, verbose_name='Estado')),
                ('created_date', models.DateTimeField(blank=True, editable=False, verbose_name='Fecha de creacion')),
                ('modified_date', models.DateTimeField(blank=True, editable=False, verbose_name='Fecha de modificacion')),
                ('deleted_date', models.DateTimeField(blank=True, editable=False, verbose_name='Fecha de eliminacion')),
                ('observacion_general', models.TextField(null=True, verbose_name='observacion_general')),
                ('dictamen', models.BooleanField(default=False, verbose_name='dictamen')),
                ('version', models.IntegerField(default=1, verbose_name='version')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('fk_protocol', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='protocol.protocol', verbose_name='fk_protocol')),
                ('fk_seleccion', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='protocol.selectprotocolo', verbose_name='fk_seleccion')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Evaluacion',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='Evaluacion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('state', models.BooleanField(default=True, verbose_name='Estado')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creacion')),
                ('modified_date', models.DateTimeField(auto_now=True, verbose_name='Fecha de modificacion')),
                ('deleted_date', models.DateTimeField(auto_now=True, verbose_name='Fecha de eliminacion')),
                ('observacion_general', models.TextField(null=True, verbose_name='observacion_general')),
                ('dictamen', models.BooleanField(default=False, verbose_name='dictamen')),
                ('version', models.IntegerField(default=1, verbose_name='version')),
                ('fk_protocol', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='protocol.protocol', verbose_name='fk_protocol')),
                ('fk_seleccion', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='protocol.selectprotocolo', verbose_name='fk_seleccion')),
            ],
            options={
                'verbose_name': 'Evaluacion',
                'verbose_name_plural': 'Evaluacion',
            },
        ),
    ]
