# Generated by Django 3.2.6 on 2022-05-02 06:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0002_initial'),
        ('protocol', '0006_auto_20220502_0004'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historicalprotocol',
            old_name='inscripccion',
            new_name='fk_inscripccion',
        ),
        migrations.RenameField(
            model_name='historicalprotocol',
            old_name='periodo',
            new_name='fk_periodo',
        ),
        migrations.RenameField(
            model_name='historicalprotocol',
            old_name='protocol_state',
            new_name='fk_protocol_state',
        ),
        migrations.RenameField(
            model_name='protocol',
            old_name='inscripccion',
            new_name='fk_inscripccion',
        ),
        migrations.RenameField(
            model_name='protocol',
            old_name='periodo',
            new_name='fk_periodo',
        ),
        migrations.RenameField(
            model_name='protocol',
            old_name='protocol_state',
            new_name='fk_protocol_state',
        ),
        migrations.AddField(
            model_name='historicalprotocol',
            name='fk_team',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='team.team', verbose_name='Equipo de protocolo'),
        ),
        migrations.AddField(
            model_name='protocol',
            name='fk_team',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='team.team', verbose_name='Equipo de protocolo'),
        ),
    ]
