# Generated by Django 3.2.6 on 2022-03-07 07:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('protocol', '0006_auto_20220307_0746'),
    ]

    operations = [
        migrations.AlterField(
            model_name='protocol',
            name='protocol_state',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='protocol.protocolstate', verbose_name='Estado del prtocolo'),
        ),
    ]
