# Generated by Django 3.2.6 on 2022-05-23 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('protocol', '0007_historicalpregunta_pregunta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalpregunta',
            name='observacion',
            field=models.TextField(blank=True, default='', null=True, verbose_name='observacion'),
        ),
        migrations.AlterField(
            model_name='pregunta',
            name='observacion',
            field=models.TextField(blank=True, default='', null=True, verbose_name='observacion'),
        ),
    ]
