# Generated by Django 3.2.6 on 2022-05-23 20:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('protocol', '0008_auto_20220523_1505'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evaluacion',
            name='fk_protocol',
        ),
        migrations.RemoveField(
            model_name='historicalevaluacion',
            name='fk_protocol',
        ),
    ]
