# Generated by Django 3.2.6 on 2022-04-05 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('protocol', '0008_alter_protocol_protocol_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalprotocol',
            name='fileProtocol',
            field=models.TextField(blank=True, max_length=100, null=True, verbose_name='Archivo de protocolo'),
        ),
        migrations.AddField(
            model_name='protocol',
            name='fileProtocol',
            field=models.FileField(blank=True, null=True, upload_to='protocolos/', verbose_name='Archivo de protocolo'),
        ),
    ]
