# Generated by Django 3.2.6 on 2022-04-06 04:11

import apps.protocol.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('protocol', '0009_auto_20220405_2305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='protocol',
            name='fileProtocol',
            field=models.FileField(blank=True, null=True, upload_to=apps.protocol.models.user_directory_path, verbose_name='Archivo de protocolo'),
        ),
    ]
