# Generated by Django 3.2.6 on 2022-05-24 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('protocol', '0010_auto_20220523_2313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evaluacion',
            name='observacion_general',
            field=models.TextField(blank=True, default='', null=True, verbose_name='observacion_general'),
        ),
        migrations.AlterField(
            model_name='historicalevaluacion',
            name='observacion_general',
            field=models.TextField(blank=True, default='', null=True, verbose_name='observacion_general'),
        ),
    ]
