# Generated by Django 3.2.6 on 2022-05-26 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('protocol', '0011_auto_20220523_2314'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalprotocol',
            name='dictamen',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='dictamen'),
        ),
        migrations.AddField(
            model_name='protocol',
            name='dictamen',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='dictamen'),
        ),
    ]
