# Generated by Django 3.2.6 on 2022-04-07 06:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('protocol', '0011_historicalkeyword_keyword'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalkeyword',
            name='fk_Protocol',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='protocol.protocol', verbose_name='pk de prtocolo'),
        ),
        migrations.AlterField(
            model_name='historicalkeyword',
            name='word',
            field=models.CharField(db_index=True, max_length=10, verbose_name='Palabra clave'),
        ),
        migrations.AlterField(
            model_name='keyword',
            name='fk_Protocol',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='protocol.protocol', verbose_name='pk de prtocolo'),
        ),
        migrations.AlterField(
            model_name='keyword',
            name='word',
            field=models.CharField(max_length=10, unique=True, verbose_name='Palabra clave'),
        ),
    ]
