# Generated by Django 3.2.6 on 2022-04-07 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('protocol', '0012_auto_20220407_0122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalkeyword',
            name='word',
            field=models.CharField(db_index=True, max_length=50, verbose_name='Palabra clave'),
        ),
        migrations.AlterField(
            model_name='keyword',
            name='word',
            field=models.CharField(max_length=50, unique=True, verbose_name='Palabra clave'),
        ),
    ]
