# Generated by Django 3.2.12 on 2022-03-31 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalteam',
            name='nombre',
            field=models.CharField(max_length=10, verbose_name='Nombre equipo'),
        ),
        migrations.AlterField(
            model_name='team',
            name='nombre',
            field=models.CharField(max_length=10, verbose_name='Nombre equipo'),
        ),
    ]
