# Generated by Django 3.2.12 on 2022-03-31 22:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('team', '0003_auto_20220331_2150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalteam',
            name='pk_user',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Creador de equipo'),
        ),
        migrations.AlterField(
            model_name='team',
            name='pk_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Creador de equipo'),
        ),
    ]
