# Generated by Django 3.2.12 on 2022-03-31 22:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0004_auto_20220331_2201'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalteam',
            name='pk_user',
        ),
        migrations.RemoveField(
            model_name='team',
            name='pk_user',
        ),
    ]
