# Generated by Django 3.2.6 on 2022-04-14 02:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('team', '0005_auto_20220331_2205'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalteam',
            name='fk_user',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='pk de usuario'),
        ),
        migrations.AddField(
            model_name='team',
            name='fk_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='pk de usuario'),
        ),
        migrations.AlterField(
            model_name='historicalteam',
            name='nombre',
            field=models.CharField(max_length=50, verbose_name='Nombre equipo'),
        ),
        migrations.AlterField(
            model_name='team',
            name='nombre',
            field=models.CharField(max_length=50, verbose_name='Nombre equipo'),
        ),
    ]
