# Generated by Django 3.2.6 on 2022-04-15 19:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('team', '0006_auto_20220413_2120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='fk_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.user', verbose_name='pk de usuario'),
        ),
    ]
