# Generated by Django 3.2.6 on 2022-04-26 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0012_auto_20220424_1804'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalteam',
            name='created_date',
            field=models.DateTimeField(blank=True, editable=False, verbose_name='Fecha de creacion'),
        ),
        migrations.AlterField(
            model_name='historicalteammembers',
            name='created_date',
            field=models.DateTimeField(blank=True, editable=False, verbose_name='Fecha de creacion'),
        ),
        migrations.AlterField(
            model_name='team',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creacion'),
        ),
        migrations.AlterField(
            model_name='teammembers',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creacion'),
        ),
    ]
